# air.toml
# Config file for air: https://github.com/air-verse/air

root = "."
tmp_dir = "tmp"

[build]
  # The command to build your app
  cmd = "go build -o ./tmp/main ."
  # The binary to run
  bin = "./tmp/main"
  # Watch these file extensions
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Include these directories
  include_dir = ["cmd", "internal"]
  # Ignore these directories
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
  # Log file for build errors
  log = "air-errors.log"
  # Delay between rebuilds
  delay = 1000 # ms

[log]
  # Show log time
  time = true

[misc]
  # Delete tmp folder on exit
  clean_on_exit = true
