root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
bin = "./tmp/main"
full_bin = ""
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "node_modules", ".git"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_root = true

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
